# Generated by Django 5.2 on 2025-04-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField(verbose_name="用户消息")),
                ("bot_message", models.TextField(verbose_name="机器人回复")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "model_metadata",
                    models.JSONField(default=dict, verbose_name="模型元数据"),
                ),
            ],
            options={
                "verbose_name": "聊天记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="app_chathis_timesta_113c60_idx"
                    )
                ],
            },
        ),
    ]
