# Generated by Django 5.2 on 2025-04-20 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="对话ID",
                    ),
                ),
                ("messages", models.JSONField(default=list, verbose_name="对话消息")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
                ),
                (
                    "model_metadata",
                    models.JSONField(default=dict, verbose_name="模型元数据"),
                ),
            ],
            options={
                "verbose_name": "聊天记录",
                "verbose_name_plural": "聊天记录",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id"],
                        name="app_chathis_convers_3d8aa0_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="app_chathis_timesta_113c60_idx"
                    ),
                ],
            },
        ),
    ]
